services:
  - type: web
    name: avm-analytics
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: NPY_NUM_BUILD_JOBS
        value: "4"
      - key: OPENBLAS_NUM_THREADS
        value: "4"
    healthCheckPath: /
    autoDeploy: true
    plan: free

    # Specify the minimum and maximum number of instances
    scaling:
      minInstances: 1
      maxInstances: 1